name: corpora
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - faiss-gpu
  - scikit-learn
  - fasttext
  - numpy=1.24.4
  - pip
  - pip:
    - charset-normalizer
    - lxml
    - pycountry
    - sentence-transformers
    - mwxml
    - mwparserfromhell