[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "corpusFromWikipedia"
version = "0.9.0"
description = "Tool to create corpora from Wikipedia dumps"
requires-python = ">= 3.10"
dependencies = [
    "faiss-gpu",
    "scikit-learn",
    "fasttext",
    "numpy>=1.25",
    "charset-normalizer",
    "lxml",
    "pycountry",
    "sentence-transformers",
    "mwxml",
    "mwparserfromhell",
    "stanza"
]

[project.scripts]
corpus-from-wikipedia = "cfw.cli:cli"
cfw = "cfw.cli:cli"

[tool.setuptools.packages.find]
where = ["."]
